#!/bin/sh

set -e
# Start up Apache24
# Since there is no sane way to get the parsed apache2 config in scripts, some
# settings are defined via environment variables and then used in apache2ctl,
# /etc/init.d/apache2, /etc/logrotate.d/apache2, etc.
export APACHE_RUN_USER=apache
export APACHE_RUN_GROUP=www-data
# temporary state file location. This might be changed to /run in Wheezy+1
export APACHE_PID_FILE=/web/run/apache2.pid
export APACHE_RUN_DIR=/var/run/
export APACHE_LOCK_DIR=/var/lock/
# Only /var/log/apache2 is handled by /etc/logrotate.d/apache2.
export APACHE_LOG_DIR=/web/log/

## The locale used by some modules like mod_dav
export LANG=C
export LANG

exec /usr/sbin/httpd -DNO_DETACH -f /web/config/httpd.conf

